# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request_target:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow-1-after:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/blank-after1.yml
    with:
      forked: true
    secrets: inherit
  call-workflow-2-after:
    uses: ./.github/workflows/blank-after2.yml
    with:
      forked: true
    secrets: inherit
